export interface CartorioInterface {
    id_cartorio: number,
    nome_cartorio: string,
    cnpj_cartorio: string,
    situacao: string,
    provimento: string,
    data_provimento: any,
    cpf_oficial: string,
    cap_int: string,
    endereco: string,
    num: string,
    bairro: string,
    cep: string,
    cidade: string,
    e_mail_principal: string,
    e_mail_secundario: string,
    telefone1: string,
    telefone2: string,
    site: string,
    
    dt_inc: any,
    usr_inc: string,
    ip_inc: string,
    dt_alt: any,
    usr_alt: string,
    ip_alt: string,
    qtde_alt: number,
    dt_ina: any,
    usr_ina: string,
    ip_ina: string
}
